### ISSUE TITLE
rebootの後にErasing

### ISSUE THREAD

**Issue by Name2889** [Kobold831/EasyBLU#1]
こんばんは。
チャレンジパッドNeo、ビルドは01.00.000です。
すべてのステップをちゃんとやりましたが、ブートローダーがアンロックされたかどうかわかりません。これをどうやって確認できますでしょうか。
他のstep-by-stepガイドも試してみまし, permissiveも確認できました。パッチ済みのboot.imgなどをフラッシュして、再起動すると、2回ぐらい自動で再起動して、"Erasing"と表示され、最初の設定画面に戻ってしまいます。

その前にビルド01.11.000では成功しましたが、01.00.000では最後のステップで止まっています（"Erasing"になって、初めの設定画面に戻ってしまいます）。
解放する方法を教えていただけますでしょうか。
ありがとうございます。

よろしくお願いいたします。

**Comment by Kobold831** [comment]
技術的な質問につきましては、SmileTabLaboで質問すると解決するかと思われます。
よろしくお願いいたします。
